### ISSUE TITLE
Bug Report: This Project is too Cool

### ISSUE THREAD

**Issue by afewvowels** [vikasbhvsr/dadjokes#1]
# Happy new year Vikas, hope all is well in CA!
![Happy 2020!](https://fdn.gsmarena.com/imgroot/news/19/12/happy-new-year/-727/gsmarena_002.jpg)

**Comment by vikasbhvsr** [comment]
Hahaha I’m like what bug in such silly project. Happy new year man. All is well in CA land. How about you there? I see you have been doing React a lot lately?

**Comment by vikasbhvsr** [comment]
> # Happy new year Vikas, hope all is well in CA!
> ![Happy 2020!](https://camo.githubusercontent.com/adcaa25c799d8692a06b02de7813af297a0be343/68747470733a2f2f66646e2e67736d6172656e612e636f6d2f696d67726f6f742f6e6577732f31392f31322f68617070792d6e65772d796561722f2d3732372f67736d6172656e615f3030322e6a7067)

Hahaha I’m like what bug in such silly project. Happy new year man. All is well in CA land. How about you there? I see you have been doing React a lot lately?

**Comment by afewvowels** [comment]
Things are all good here, we talked my grandma into coming to wintery PA for three weeks (don't ask me how) so I've been eating well and it was sad to see her go back to CA. I've been trying to get other people on board the React train and I even started on a React Native mobile app--it's pretty sick being able to style using CSS, way better than Xamarin. With Electron gaining steam too it seems like everything's going js, html & css. Hope you have a great New Year!

**Comment by vikasbhvsr** [comment]
I guess that means you will soon visit CA. No experience with any .NET frameworks, etc. Do you still prefer .NET over open-source JS stuff?

Wish you a great new year as well.

**Comment by afewvowels** [comment]
Dude, [it's open-source!](https://dotnet.microsoft.com/) But you'll probably want to wait a year to get into it. Right now there's Xamarin (for mobile), .NET Framework, .NET Core, and a bunch of others which is a total mess. But with [.NET 5](https://devblogs.microsoft.com/dotnet/introducing-net-5/) they're boiling all of it down into a single framework, so that should be a real good time. I really like doing this cross-platform stuff. I've been programming in Unity a lot and the idea of writing once and pushing to [25 different platforms](https://unity3d.com/unity/features/multiplatform) is pretty great.

Anywho, I hope you have a great year, 2020 should be a real blast!
